agendamento/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from conta import urls
from cliente import urls
from consultor import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('core/', include('core.urls')),
    path('conta/', include('conta.urls')),
    path('cliente/', include('cliente.urls')),
    path('consultor/', include('consultor.urls'))
]

cliente/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('lista_cliente/', views.lista_cliente, name='lista_cliente'),
]

consultor/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('lista_consultor/', views.lista_consultor, name='lista_consultor'),
    path('lista_servico/', views.lista_servico, name='lista_servico'),
]

core/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('cliente/', views.cliente, name='cliente'),
    path('consultor/', views.consultor, name='consultor'),
    path('servico/', views.servico, name='servico'),
    path('agenda/', views.agenda, name='agenda'),
    path('lista/', views.lista, name='lista'),
    path('editar/<int:id_agenda>/', views.editar, name='editar'),
    path('deletar/<int:id_agenda>/', views.deletar, name='deletar'),
    path('edita_cliente/<int:id_cliente>/', views.edita_cliente, name='edita_cliente'),
    path('deleta_cliente/<int:id_cliente>/', views.deleta_cliente, name='deleta_cliente'),
    path('edita_cliente_home/<int:id_cliente>/', views.edita_cliente_home, name='edita_cliente_home'),
    path('deleta_cliente_home/<int:id_cliente>/', views.deleta_cliente_home, name='deleta_cliente_home'),
    path('edita_consultor/<int:id_consultor>/', views.edita_consultor, name='edita_consultor'),
    path('deleta_consuktor<int:id_consultor>/', views.deleta_consultor, name='deleta_consultor'),
    path('edita_servico/<int:id_servico>/', views.edita_servico, name='edita_servico'),
    path('deleta_servico/<int:id_servico>/', views.deleta_servico, name='deleta_servico'),
    path('edita_usuario/<int:id_user>/', views.edita_usuario, name='edita_usuario'),
    path('deleta_usuario/<int:id_user>/', views.deleta_usuario, name='deleta_usuario'),
    
]

agenda/models.py
from django.db import models
from cliente.models import Pessoa
from consultor.models import Consultor, Servico

class Agenda(models.Model):
	cliente = models.ForeignKey(Pessoa, on_delete=models.CASCADE,null=True,blank=True)
	consultor = models.ForeignKey(Consultor, on_delete=models.CASCADE,null=True,blank=True)
	servico = models.ForeignKey(Servico, on_delete=models.CASCADE,null=True,blank=True)
	data = models.DateField(auto_now_add=False, null=True)
	hora = models.TimeField(auto_now_add=False, null=True)
	status = (
		('A', 'Aberto'),
		('E', 'Andamento'),
		('F', 'Fechado'),
		)
	status = models.CharField('Status', max_length=1, choices=status, null=True,blank=True)
	preco = models.DecimalField('Preço', max_digits=7, decimal_places=2,null=True,blank=True)
	pag = (
    	('D', 'Dinheiro'),
    	('CD', 'Cartão Debito'),
    	('CC', 'Cartão Credito'),
    	)
	pagamento = models.CharField('Pagamento', max_length=2, choices=pag, null=True,blank=True)
	class Meta:
		verbose_name_plural = 'Agendas'
		verbose_name = 'Agenda'

	

	def __str__(self):
		return "%s" % self.cliente

cliente/models.py
from django.db import models


class Pessoa(models.Model):
	nome = models.CharField('Nome', max_length=100,blank=True)
	cpf = models.CharField('CPF', max_length=14,blank=True)
	telefone = models.CharField('Telefone', max_length=9,blank=True)
	endereco = models.CharField('Endereco', max_length=250,blank=True)
	cep = models.CharField('CEP', max_length=13,blank=True)
	cidade = models.CharField('Cidade', max_length=100,blank=True)
	bairro = models.CharField('Bairro', max_length=100,blank=True)
	estado = models.CharField('estado', max_length=2,blank=True)
	email = models.EmailField('Email', max_length=200,blank=True)

	class Meta:
		verbose_name_plural = 'Clientes'
		verbose_name = 'Cliente'

	def __str__(self):
		return self.nome

consultor/models.py
from django.db import models


class Consultor(models.Model):
	nome = models.CharField('Consultor', max_length=100,blank=True)
	telefone = models.CharField('Telefone', max_length=9,blank=True)

	class Meta:
		verbose_name = 'Consultor'
		verbose_name_plural = 'Consultores'

	def __str__(self):
		return self.nome

class Servico(models.Model):
	nome = models.CharField('Seviço', max_length=100)
	pag = (
    	('D', 'Dinheiro'),
    	('CD', 'Cartão Debito'),
    	('CC', 'Cartão Credito'),
    	)
	pagamento = models.CharField('Pagamento', max_length=2, choices=pag,blank=True)
	valor_servico = models.CharField('Valor Serviço', max_length=100,blank=True)
	class Meta:
		verbose_name = 'Serviço'
		verbose_name_plural = 'Serviços'

	def __str__(self):
		return self.nome

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.forms import ModelForm
from cliente.models import Pessoa
from consultor.models import Consultor, Servico
from agenda.models import Agenda

class ClienteForm(ModelForm):
	class Meta:
		model = Pessoa
		fields = '__all__'

class ConsultorForm(ModelForm):
	class Meta:
		model = Consultor
		fields = '__all__'

class ServicoForm(ModelForm):
	class Meta:
		model = Servico
		fields = '__all__'

class AgendaForm(ModelForm):
	class Meta:
		model = Agenda
		fields = '__all__'

agenda/views.py
from django.shortcuts import render

# Create your views here.

cliente/views.py
from django.shortcuts import render
from cliente.models import Pessoa
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def lista_cliente(request):
	relacao = Pessoa.objects.all()
	paginator = Paginator(relacao,5)
	page = request.GET.get('page')
	relacao = paginator.get_page(page)
	return render(request, 'core/lista_cliente.html',{'relacao':relacao})

consultor/views.py
from django.shortcuts import render
from consultor.models import Consultor, Servico
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def lista_consultor(request):
	relacao = Consultor.objects.all()
	paginator = Paginator(relacao,5)
	page = request.GET.get('page')
	relacao = paginator.get_page(page)
	return render(request, 'core/lista_consultor.html',{'relacao':relacao})


def lista_servico(request):
	relacao = Servico.objects.all()
	paginator = Paginator(relacao,5)
	page = request.GET.get('page')
	relacao = paginator.get_page(page)
	return render(request, 'core/lista_servico.html',{'relacao':relacao})

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cliente.models import Pessoa
from consultor.models import Consultor, Servico
from .forms import ClienteForm, ConsultorForm, ServicoForm, AgendaForm
from conta.forms import UsuarioForm, User
from agenda.models import Agenda
from datetime import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
	data = datetime.now()
	lista = Pessoa.objects.all()
	total_clientes = Pessoa.objects.count()
	total_servicos = Servico.objects.count()
	total_agendamentos = Agenda.objects.count()
	total_consultores = Consultor.objects.count()
	paginator = Paginator(lista,5)
	page = request.GET.get('page')
	lista = paginator.get_page(page)
	return render(request, 'index.html',{'lista':lista,'data':data,'total_clientes':total_clientes,'total_servicos':total_servicos,
	'total_agendamentos':total_agendamentos,'total_consultores':total_consultores})


def base(request):
	data_base = datetime.now()
	return render(request,'base.html',{'data_base':data_base})

@login_required
def cliente(request):
	if request.method == 'POST':
		form = ClienteForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
	else:
		form = ClienteForm()
	return render(request, 'core/clienteform.html',{'form':form})

@login_required
def consultor(request):
	if request.method == 'POST':
		form = ConsultorForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
	else:
		form = ConsultorForm()
	return render(request, 'core/consultorform.html',{'form':form})

@login_required
def servico(request):
	if request.method == 'POST':
		form = ServicoForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
	else:
		form = ServicoForm()
	return render(request, 'core/servicoform.html',{'form':form})

@login_required
def agenda(request):
	if request.method == 'POST':
		form = AgendaForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('lista')
	else:
		form = AgendaForm()
	return render(request, 'core/agendaform.html',{'form':form})

@login_required
def lista(request):
	relacao = Agenda.objects.all()
	paginator = Paginator(relacao,5)
	page = request.GET.get('page')
	relacao = paginator.get_page(page)
	return render(request, 'core/lista.html',{'relacao':relacao})

@login_required
def editar(request, id_agenda):
	edite = get_object_or_404(Agenda, id=id_agenda)
	if request.method == 'POST':
		form = AgendaForm(request.POST, instance=edite)
		if form.is_valid():
			form.save()
			return redirect('lista')
	else:
		form = AgendaForm(instance=edite)
	return render(request, 'core/agendaform.html',{'form':form})

@login_required
def deletar(request, id_agenda):
	exclui = Agenda.objects.get(id=id_agenda).delete()
	return redirect('lista')

@login_required
def edita_cliente_home(request, id_cliente):
	ed = get_object_or_404(Pessoa, id=id_cliente)
	if request.method == 'POST':
		form = ClienteForm(request.POST, instance=ed)
		if form.is_valid():
			form.save()
			return redirect('home')
	else:
		form = ClienteForm(instance=ed)
	return render(request, 'core/clienteform.html',{'form':form})
	
@login_required
def deleta_cliente_home(request, id_cliente):
	exclui_cliente = Pessoa.objects.get(id=id_cliente).delete()
	return redirect('home')

@login_required
def edita_cliente(request, id_cliente):
	ed = get_object_or_404(Pessoa, id=id_cliente)
	if request.method == 'POST':
		form = ClienteForm(request.POST, instance=ed)
		if form.is_valid():
			form.save()
			return redirect('lista_cliente')
	else:
		form = ClienteForm(instance=ed)
	return render(request, 'core/clienteform.html',{'form':form})
	
@login_required
def deleta_cliente(request, id_cliente):
	exclui_cliente = Pessoa.objects.get(id=id_cliente).delete()
	return redirect('lista_cliente')


#Editar Consultor
@login_required
def edita_consultor(request, id_consultor):
	ed = get_object_or_404(Consultor, id=id_consultor)
	if request.method == 'POST':
		form = ConsultorForm(request.POST, instance=ed)
		if form.is_valid():
			form.save()
			return redirect('lista_consultor')
	else:
		form = ConsultorForm(instance=ed)
	return render(request, 'core/consultorform.html',{'form':form})
	
@login_required
def deleta_consultor(request, id_consultor):
	exclui_consultor = Consultor.objects.get(id=id_consultor).delete()
	return redirect('lista_consultor')


#Editar Servico
@login_required
def edita_servico(request, id_servico):
	ed = get_object_or_404(Servico, id=id_servico)
	if request.method == 'POST':
		form = ServicoForm(request.POST, instance=ed)
		if form.is_valid():
			form.save()
			return redirect('lista_servico')
	else:
		form = ServicoForm(instance=ed)
	return render(request, 'core/servicoform.html',{'form':form})
	
@login_required
def deleta_servico(request, id_servico):
	exclui_servico = Servico.objects.get(id=id_servico).delete()
	return redirect('lista_servico')

#Editar Usuário
@login_required
def edita_usuario(request, id_user):
	ed = get_object_or_404(User, id=id_user)
	if request.method == 'POST':
		form = UsuarioForm(request.POST, instance=ed)
		if form.is_valid():
			form.save()
			return redirect('lista_usuario')
	else:
		form = UsuarioForm(instance=ed)
	return render(request, 'conta/add_usuario.html',{'form':form})
	
@login_required
def deleta_usuario(request, id_user):
	exclui_usuario = User.objects.get(id=id_user).delete()
	return redirect('lista_usuario')

core/templates/core/agendaform.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
    <br>
    <h2><strong> Cadastrar Agendamentos </strong></h2>
    <br>
	<form method="post">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.cliente.id_for_label }}">Cliente:</label>
                   {{ form.cliente|add_class:"form-control" }}
				</div>
			</div>
		
			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.consultor.id_for_label }}">Consultor:</label>
                   {{ form.consultor|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.servico.id_for_label }}">Serviço:</label>
                   {{ form.servico|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.data.id_for_label }}">Data:</label>
                   {{ form.data|add_class:"form-control"|attr:"type:date" }}
				</div>
			</div>

			<div class="col-md-6">

				<div class="form-group">
					<label for="{{ form.hora.id_for_label }}">Horário :</label>
                   {{ form.hora|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.preco.id_for_label }}">Valor R$:</label>
                   {{ form.preco|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.pagamento.id_for_label }}">Pagamento :</label>
                   {{ form.pagamento|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.status.id_for_label }}">Status :</label>
                   {{ form.status|add_class:"form-control"}}
				</div>
			</div>
		
			<div class="col-md-12">
				<button class="btn btn-success" type="submit"> Salvar </button>
				<a href="{% url 'home' %}" class="btn btn-danger" type="submit"> Cancelar </a>
			</div>
		
	</form>
{% endblock body %}

core/templates/core/clienteform.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
    <br>
    <h2><strong> Cadastrar Clientes </strong></h2>
    <br>
	<form method="post">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-2">
				<div class="form-group">
					<label for="{{ form.cpf.id_for_label }}">CPF :</label>
                   {{ form.cpf|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-10">
				<div class="form-group">
					<label for="{{ form.nome.id_for_label }}">Nome :</label>
                   {{ form.nome|add_class:"form-control" }}
				</div>
			</div>
		
		
			<div class="col-md-2">
				<div class="form-group">
					<label for="{{ form.telefone.id_for_label }}">Telefone :</label>
                   {{ form.telefone|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-10">
				<div class="form-group">
					<label for="{{ form.endereco.id_for_label }}">Endereço :</label>
                   {{ form.endereco|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-2">
				<div class="form-group">
					<label for="{{ form.cep.id_for_label }}">CEP :</label>
                   {{ form.cep|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-4">
				<div class="form-group">
					<label for="{{ form.bairro.id_for_label }}">Bairro :</label>
                   {{ form.bairro|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.cidade.id_for_label }}">Cidade :</label>
                   {{ form.cidade|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-2">
				<div class="form-group">
					<label for="{{ form.estado.id_for_label }}">Estado :</label>
                   {{ form.estado|add_class:"form-control" }}
				</div>
			</div>
			
			<div class="col-md-10">
				<div class="form-group">
					<label for="{{ form.email.id_for_label }}">Email :</label>
                   {{ form.email|add_class:"form-control" }}
				</div>
			</div>

			<div class="col-md-12">
				<button class="btn btn-success" type="submit"> Salvar </button>
				<a href="{% url 'home' %}" class="btn btn-danger" type="submit"> Cancelar </a>
			</div>
		
	</div>
		
	</form>
{% endblock body %}

core/templates/core/consultorform.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <br>
    <h2><strong> Cadastrar Consultores </strong></h2>
    <br>
	<form method="post">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.nome.id_for_label }}">Nome :</label>
                   {{ form.nome|add_class:"form-control" }}
				</div>
			</div>
		
			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.telefone.id_for_label }}">Telefone :</label>
                   {{ form.telefone|add_class:"form-control" }}
				</div>
			</div>
		
			<div class="col-md-6">
				<button class="btn btn-success" type="submit"> Salvar </button>
				<a href="{% url 'home' %}" class="btn btn-danger" type="submit"> Cancelar </a>
			</div>
		
	</form>
{% endblock body %}

core/templates/core/editar_usuario.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<style type="text/css">
.alert {
padding: 0 15px;
margin-bottom: 1rem;
border: 1px solid transparent;
border-radius: .25rempx
}
.alert p{
padding: 7px 0 7px;
}
.alert.success{
color: #3c763d;
background-color: #dff0d8;
border-color: #d0e9c6;}
</style>
<br>
<br>
 <div class="row">
 <div class="col-lg-12">
 <div class="panel panel-default">
 <div class="panel-heading">
  <strong>Listar Funcionários</strong>
  </div>
   
   <div class="panel-body">
   <div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
    <thead>
                                               
    <tr>
    
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Usuário</th>
    <th>Editar</th>
    <th>Deletar</th>
    </tr>
    </thead>
    <tbody>
    {% for list in relacao %}
    <tr>
    
    <td>{{list.first_name}}</td>
    <td>{{list.last_name}}</td>
    <td>{{list.username}}</td>
    <td><a href="{% url 'edita_usuario' list.id %}" class="btn btn-info">Editar</a></td>
    <td><a href="{% url 'deleta_usuario' list.id %}" class="btn btn-danger">Deletar</a></td>
    </tr>
    {% empty %}
    <div class="alert danger">
    <p>Nenhum funcionário cadastrado encontrado</p>
    </div>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="text-info">
    <span class="step-links">
    {% if relacao.has_previous %}
    <a href="?page=1"></a>
    <a class="text-info" href="?page={{ relacao.previous_page_number }}"> Anterior </a>
    {% endif %}
    <span class="current">
    Paginas {{ relacao.number }} de {{ relacao.paginator.num_pages }}
    </span>
    {% if relacao.has_next %}
    <a class="text-info" href="?page={{ relacao.next_page_number }}"> Próxima </a>
    <a href="?page={{ relacao.paginator.num_pages }}"></a>
    {% endif %}
    </span>
    </div>
{% endblock body %}

core/templates/core/lista.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<style type="text/css">
.alert {
padding: 0 15px;
margin-bottom: 1rem;
border: 1px solid transparent;
border-radius: .25rempx
}
.alert p{
padding: 7px 0 7px;
}
.alert.success{
color: #3c763d;
background-color: #dff0d8;
border-color: #d0e9c6;}
</style>
<br>
<br>
 <div class="row">
 <div class="col-lg-12">
 <div class="panel panel-default">
 <div class="panel-heading">
  <strong>Listar Agendamentos</strong>
  </div>
   
   <div class="panel-body">
   <div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
    <thead>
                                               
    <tr>
    
    <th>Cliente</th>
    <th>Consultor</th>
    <th>Serviço</th>
    <th>Data</th>
    <th>Hora</th>
    <th>Status</th>
    <th>Valor R$</th>
    <th>Forma PG.</th>
    <th>Editar</th>
    <th>Deletar</th>
    </tr>
    </thead>
    <tbody>
    {% for list in relacao %}
    <tr>
    
    <td>{{list.cliente}}</td>
    <td>{{list.consultor}}</td>
    <td>{{list.servico}}</td>
    <td>{{list.data}}</td>
    <td>{{list.hora}}</td>
    <td>{{list.get_status_display}}</td>
    <td>{{list.preco}}</td>
    <td>{{list.get_pagamento_display}}</td>
    <td><a href="{% url 'editar' list.id %}" class="btn btn-info">Editar</a></td>
    <td><a href="{% url 'deletar' list.id %}" class="btn btn-danger">Deletar</a></td>
    </tr>
    {% empty %}
    <div class="alert danger">
    <p>Sem agendamentos no momento</p>
    </div>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="text-info">
    <span class="step-links">
    {% if relacao.has_previous %}
    <a href="?page=1"></a>
    <a class="text-info" href="?page={{ relacao.previous_page_number }}"> Anterior </a>
    {% endif %}
    <span class="current">
    Paginas {{ relacao.number }} de {{ relacao.paginator.num_pages }}
    </span>
    {% if relacao.has_next %}
    <a class="text-info" href="?page={{ relacao.next_page_number }}"> Próxima </a>
    <a href="?page={{ relacao.paginator.num_pages }}"></a>
    {% endif %}
    </span>
    </div>
{% endblock body %}

core/templates/core/lista_cliente.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<style type="text/css">
.alert {
padding: 0 15px;
margin-bottom: 1rem;
border: 1px solid transparent;
border-radius: .25rempx
}
.alert p{
padding: 7px 0 7px;
}
.alert.success{
color: #3c763d;
background-color: #dff0d8;
border-color: #d0e9c6;}
</style>
<br>
<br>
 <div class="row">
 <div class="col-lg-12">
 <div class="panel panel-default">
 <div class="panel-heading">
  <strong>Listar Clientes</strong>
  </div>
   
   <div class="panel-body">
   <div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
    <thead>
                                               
    <tr>
    
    <th>Nome</th>
    <th>CPF</th>
    <th>Telefone</th>
    <th>Editar</th>
    <th>Deletar</th>
    </tr>
    </thead>
    <tbody>
    {% for list in relacao %}
    <tr>
    
    <td>{{list.nome}}</td>
    <td>{{list.cpf}}</td>
    <td>{{list.telefone}}</td>
    <td><a href="{% url 'edita_cliente' list.id %}" class="btn btn-info">Editar</a></td>
    <td><a href="{% url 'deleta_cliente' list.id %}" class="btn btn-danger">Deletar</a></td>
    </tr>
    {% empty %}
    <div class="alert danger">
    <p>Nenhum cliente cadastrado encontrado</p>
    </div>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="text-info">
    <span class="step-links">
    {% if relacao.has_previous %}
    <a href="?page=1"></a>
    <a class="text-info" href="?page={{ relacao.previous_page_number }}"> Anterior </a>
    {% endif %}
    <span class="current">
    Paginas {{ relacao.number }} de {{ relacao.paginator.num_pages }}
    </span>
    {% if relacao.has_next %}
    <a class="text-info" href="?page={{ relacao.next_page_number }}"> Próxima </a>
    <a href="?page={{ relacao.paginator.num_pages }}"></a>
    {% endif %}
    </span>
    </div>
{% endblock body %}

core/templates/core/lista_consultor.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
<style type="text/css">
.alert {
padding: 0 15px;
margin-bottom: 1rem;
border: 1px solid transparent;
border-radius: .25rempx
}
.alert p{
padding: 7px 0 7px;
}
.alert.success{
color: #3c763d;
background-color: #dff0d8;
border-color: #d0e9c6;}
</style>
<br>
<br>
 <div class="row">
 <div class="col-lg-12">
 <div class="panel panel-default">
 <div class="panel-heading">
  <strong>Listar Consultores</strong>
  </div>
   
   <div class="panel-body">
   <div class="table-responsive">
   <table class="table table-striped table-bordered table-hover">
    <thead>
                                               
    <tr>
    
    <th>Nome</th>
    <th>Telefone</th>
    <th>Editar</th>
    <th>Deletar</th>
    </tr>
    </thead>
    <tbody>
    {% for list in relacao %}
    <tr>
    
    <td>{{list.nome}}</td>
    <td>{{list.telefone}}</td>
    <td><a href="{% url 'edita_consultor' list.id %}" class="btn btn-info">Editar</a></td>
    <td><a href="{% url 'deleta_consultor' list.id %}" class="btn btn-danger">Deletar</a></td>
    </tr>
    {% empty %}
    <div class="alert danger">
    <p>Nenhum consultor cadastrado encontrado</p>
    </div>
    {% endfor %}
    </tbody>
    </table>
    </div>
    </div>
    </div>
    </div>
    <div class="text-info">
    <span class="step-links">
    {% if relacao.has_previous %}
    <a href="?page=1"></a>
    <a class="text-info" href="?page={{ relacao.previous_page_number }}"> Anterior </a>
    {% endif %}
    <span class="current">
    Paginas {{ relacao.number }} de {{ relacao.paginator.num_pages }}
    </span>
    {% if relacao.has_next %}
    <a class="text-info" href="?page={{ relacao.next_page_number }}"> Próxima </a>
    <a href="?page={{ relacao.paginator.num_pages }}"></a>
    {% endif %}
    </span>
    </div>
{% endblock body %}

core/templates/core/servicoform.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block body %}
    <br>
    <h2><strong>Cadastrar Serviços</strong></h2>
    <br>
	<form method="post">
		{% csrf_token %}
		<div class="row">
			<div class="col-md-6">
				<div class="form-group ">
					<label for="{{ form.nome.id_for_label }}">Nome :</label>
                   {{ form.nome|add_class:"form-control" }}
				</div>
			</div>
			
			<div class="col-md-6">
				<div class="form-group ">
					<label for="{{ form.valor_servico.id_for_label }}">Valor:</label>
                   {{ form.valor_servico|add_class:"form-control" }}
				</div>
			</div>
		
			<div class="col-md-6">
				<button class="btn btn-success" type="submit"> Salvar </button>
				<a href="{% url 'home' %}" class="btn btn-danger" type="submit"> Cancelar </a>
			</div>
				   
	</form>
{% endblock body %}